# Generated by Django 5.2.6 on 2025-09-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('wind_triangle', 'Wind Triangle'), ('great_circle', 'Great Circle'), ('rhumb_line', 'Rhumb Line')], max_length=20)),
                ('inputs', models.JSONField()),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
